postfix: metric_learning

seed: 42
precision: 32
accelerator: gpu
devices: 1

dataframe_name: df.csv
dataset_root: /data/zool-songbird/shil5293/projects/open-metric-learning/examples/datasets/GRETI
logs_root: logs/GRETI
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_albu
  args:
    im_size: 224

transforms_val:
  name: norm_resize_albu
  args:
    im_size: 224

sampler:
  name: balance
  args:
    n_labels: 8
    n_instances: 4

bs_val: 256
max_epochs: 30 # was 1000
valid_period: 5
log_every_n_steps: 5

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1]
  map_top_k: [5]
  fmr_vals: [0.01]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_main_category: True
  visualize_only_main_category: True

log_images: True

metric_for_checkpointing: OVERALL/cmc/1

model:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}

optimizer:
  name: adam
  args:
    lr: 1e-5  # if you provide scheduler this parameter will be ignored

scheduling: null


# To use neptune you should also specify NEPTUNE_API_TOKEN in
# .env file or via `export NEPTUNE_API_TOKEN=...`
neptune_project: nilomr/greti


hydra_dir: ${logs_root}${logs_folder}/

tags:
  - ${postfix}
  - greti-metric-learning

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - pkg://oml.configs
